name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run-script webpack
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: main.js
        path: dist/main.js
        if-no-files-found: error
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.1
      with:
        name: main.js
        path: dist/main.js
